on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      id: setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
    - name: Print PHP version
      run: echo ${{ steps.setup-php.outputs.php-version }}
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Install dependencies
      uses: "ramsey/composer-install@v3"

    - name: PHP Code Sniffer
      uses: php-actions/phpcs@v1
      with:
        php_version: 8.2
        path: src/
        standard: phpcs.xml
